name: Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  nestor_typescript_ci:
    name: Typescript
    uses: youwol/nestor/.github/workflows/typescript-ci.yaml@v3
    with:
      skip: eslint
